[2024-12-05T00:34:51.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T00:34:51.430+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl_dag_gcp.create_bucket scheduled__2024-12-04T00:00:00+00:00 [queued]>
[2024-12-05T00:34:51.464+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl_dag_gcp.create_bucket scheduled__2024-12-04T00:00:00+00:00 [queued]>
[2024-12-05T00:34:51.467+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-05T00:34:51.526+0000] {taskinstance.py:2888} INFO - Executing <Task(GCSCreateBucketOperator): create_bucket> on 2024-12-04 00:00:00+00:00
[2024-12-05T00:34:51.576+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=46476) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T00:34:51.585+0000] {standard_task_runner.py:72} INFO - Started process 46484 to run task
[2024-12-05T00:34:51.590+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_dag_gcp', 'create_bucket', 'scheduled__2024-12-04T00:00:00+00:00', '--job-id', '514', '--raw', '--subdir', 'DAGS_FOLDER/spotify_***_gcp.py', '--cfg-path', '/tmp/tmpstn621xi']
[2024-12-05T00:34:51.595+0000] {standard_task_runner.py:105} INFO - Job 514: Subtask create_bucket
[2024-12-05T00:34:51.860+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_etl_dag_gcp.create_bucket scheduled__2024-12-04T00:00:00+00:00 [running]> on host da4c4a711107
[2024-12-05T00:34:52.073+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artika' AIRFLOW_CTX_DAG_ID='spotify_etl_dag_gcp' AIRFLOW_CTX_TASK_ID='create_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T00:00:00+00:00'
[2024-12-05T00:34:52.080+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-05T00:34:52.082+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-05T00:34:52.085+0000] {logging_mixin.py:190} INFO - Current task name:create_bucket state:running start_date:2024-12-05 00:34:51.432200+00:00
[2024-12-05T00:34:52.086+0000] {logging_mixin.py:190} INFO - Dag name:spotify_etl_dag_gcp and current dag run status:running
[2024-12-05T00:34:52.087+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T00:34:52.136+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-12-05T00:34:52.153+0000] {base.py:84} INFO - Retrieving connection 'gcp_conn_id'
[2024-12-05T00:34:52.442+0000] {gcs.py:1080} INFO - Creating Bucket: spotify-songs-album-artists-pipeline; Location: US; Storage Class: MULTI_REGIONAL
[2024-12-05T00:34:53.783+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 152, in execute
    hook.create_bucket(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 559, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 1098, in create_bucket
    bucket.create(project=project_id, location=location)
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/bucket.py", line 980, in create
    client.create_bucket(
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/client.py", line 1060, in create_bucket
    api_response = self._post_resource(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/client.py", line 715, in _post_resource
    return self._connection.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/_http.py", line 90, in api_request
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://storage.googleapis.com/storage/v1/b?project=My+Project+69232&prettyPrint=false: Unknown project id: My Project 69232
[2024-12-05T00:34:54.031+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-05T00:34:54.062+0000] {logging_mixin.py:190} INFO - Task start:2024-12-05 00:34:51.432200+00:00 end:2024-12-05 00:34:54.019976+00:00 duration:2.587776
[2024-12-05T00:34:54.065+0000] {logging_mixin.py:190} INFO - Task:<Task(GCSCreateBucketOperator): create_bucket> dag:<DAG: spotify_etl_dag_gcp> dagrun:<DagRun spotify_etl_dag_gcp @ 2024-12-04 00:00:00+00:00: scheduled__2024-12-04T00:00:00+00:00, state:running, queued_at: 2024-12-05 00:34:07.078505+00:00. externally triggered: False>
[2024-12-05T00:34:54.071+0000] {logging_mixin.py:190} INFO - Failure caused by 400 POST https://storage.googleapis.com/storage/v1/b?project=My+Project+69232&prettyPrint=false: Unknown project id: My Project 69232
[2024-12-05T00:34:54.075+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spotify_etl_dag_gcp, task_id=create_bucket, run_id=scheduled__2024-12-04T00:00:00+00:00, execution_date=20241204T000000, start_date=20241205T003451, end_date=20241205T003454
[2024-12-05T00:34:54.334+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T00:34:54.362+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 514 for task create_bucket (400 POST https://storage.googleapis.com/storage/v1/b?project=My+Project+69232&prettyPrint=false: Unknown project id: My Project 69232; 46484)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 152, in execute
    hook.create_bucket(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 559, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 1098, in create_bucket
    bucket.create(project=project_id, location=location)
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/bucket.py", line 980, in create
    client.create_bucket(
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/client.py", line 1060, in create_bucket
    api_response = self._post_resource(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/client.py", line 715, in _post_resource
    return self._connection.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/_http.py", line 90, in api_request
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://storage.googleapis.com/storage/v1/b?project=My+Project+69232&prettyPrint=false: Unknown project id: My Project 69232
[2024-12-05T00:34:54.621+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T00:34:54.957+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T00:34:54.985+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
