[2024-10-08T06:18:47.363+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T06:18:47.388+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl_dag.fetch_spotify_data manual__2024-10-08T06:13:47.327866+00:00 [queued]>
[2024-10-08T06:18:47.399+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl_dag.fetch_spotify_data manual__2024-10-08T06:13:47.327866+00:00 [queued]>
[2024-10-08T06:18:47.399+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-08T06:18:47.424+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_spotify_data> on 2024-10-08 06:13:47.327866+00:00
[2024-10-08T06:18:47.442+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T06:18:47.444+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2024-10-08T06:18:47.445+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_dag', 'fetch_spotify_data', 'manual__2024-10-08T06:13:47.327866+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/spotify_***_pipeline.py', '--cfg-path', '/tmp/tmp7ez8t9q8']
[2024-10-08T06:18:47.446+0000] {standard_task_runner.py:105} INFO - Job 347: Subtask fetch_spotify_data
[2024-10-08T06:18:47.617+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_etl_dag.fetch_spotify_data manual__2024-10-08T06:13:47.327866+00:00 [running]> on host 72c8cc140f42
[2024-10-08T06:18:47.900+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artika' AIRFLOW_CTX_DAG_ID='spotify_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_spotify_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T06:13:47.327866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T06:13:47.327866+00:00'
[2024-10-08T06:18:47.902+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-08T06:18:47.902+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-08T06:18:47.902+0000] {logging_mixin.py:190} INFO - Current task name:fetch_spotify_data state:running start_date:2024-10-08 06:18:47.389038+00:00
[2024-10-08T06:18:47.903+0000] {logging_mixin.py:190} INFO - Dag name:spotify_etl_dag and current dag run status:running
[2024-10-08T06:18:47.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T06:18:47.923+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_airflow_pipeline.py", line 26, in _fetch_spotify_data
    sp = spotipy.spotify(client_credentials_manager=client_credentials_manager)
         ^^^^^^^^^^^^^^^
AttributeError: module 'spotipy' has no attribute 'spotify'. Did you mean: 'Spotify'?
[2024-10-08T06:18:47.976+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-08T06:18:47.976+0000] {logging_mixin.py:190} INFO - Task start:2024-10-08 06:18:47.389038+00:00 end:2024-10-08 06:18:47.975049+00:00 duration:0.586011
[2024-10-08T06:18:47.977+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_spotify_data> dag:<DAG: spotify_etl_dag> dagrun:<DagRun spotify_etl_dag @ 2024-10-08 06:13:47.327866+00:00: manual__2024-10-08T06:13:47.327866+00:00, state:running, queued_at: 2024-10-08 06:13:47.412648+00:00. externally triggered: True>
[2024-10-08T06:18:47.977+0000] {logging_mixin.py:190} INFO - Failure caused by module 'spotipy' has no attribute 'spotify'
[2024-10-08T06:18:47.978+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spotify_etl_dag, task_id=fetch_spotify_data, run_id=manual__2024-10-08T06:13:47.327866+00:00, execution_date=20241008T061347, start_date=20241008T061847, end_date=20241008T061847
[2024-10-08T06:18:48.038+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T06:18:48.040+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 347 for task fetch_spotify_data (module 'spotipy' has no attribute 'spotify'; 97)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_airflow_pipeline.py", line 26, in _fetch_spotify_data
    sp = spotipy.spotify(client_credentials_manager=client_credentials_manager)
         ^^^^^^^^^^^^^^^
AttributeError: module 'spotipy' has no attribute 'spotify'. Did you mean: 'Spotify'?
[2024-10-08T06:18:48.084+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-08T06:18:48.107+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T06:18:48.108+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
